(defun c:azt_polaczenie_zakladkowe_start()
  (setq azt_aktualne_polaczenie_zakladkowe_rodzaj_sruby "12")
  (setq azt_aktualne_polaczenie_zakladkowe_ilosc_srub_w_poziomie "2")
  (setq azt_aktualne_polaczenie_zakladkowe_ilosc_srub_w_pionie "2")
)

(defun azt_polaczenie_parametry_m12 ()
  (setq azt_polaczenie_parametr_s "30")
  (setq azt_polaczenie_parametr_p "35")
  (setq azt_polaczenie_parametr_e "20")
)

(defun azt_polaczenie_parametry_m16 ()
  (setq azt_polaczenie_parametr_s "35")
  (setq azt_polaczenie_parametr_p "45")
  (setq azt_polaczenie_parametr_e "25")
)

(defun azt_polaczenie_parametry_m20 ()
  (setq azt_polaczenie_parametr_s "35")
  (setq azt_polaczenie_parametr_p "45")
  (setq azt_polaczenie_parametr_e "25")
)

(defun azt_polaczenie_parametry_m24 ()
  (setq azt_polaczenie_parametr_s "50")
  (setq azt_polaczenie_parametr_p "60")
  (setq azt_polaczenie_parametr_e "35")
)

(defun azt_polaczenie_parametry_m30 ()
  (setq azt_polaczenie_parametr_s "60")
  (setq azt_polaczenie_parametr_p "80")
  (setq azt_polaczenie_parametr_e "45")
)

(defun azt_polaczenie_zakladkowe_parametry ()
  (setq azt_polaczenie_zakladkowe_rodzaj_sruby (getstring (strcat "\nPodaj srednice trzpienia sruby (MXX) [12/16/20/24/30]: <" azt_aktualne_polaczenie_zakladkowe_rodzaj_sruby ">")))
  (if (equal azt_polaczenie_zakladkowe_rodzaj_sruby "")
      (setq azt_polaczenie_zakladkowe_rodzaj_sruby azt_aktualne_polaczenie_zakladkowe_rodzaj_sruby)
      (princ)
  )
  (if (equal azt_polaczenie_zakladkowe_rodzaj_sruby "12")
      (azt_polaczenie_parametry_m12)
      (princ)
  )
  (if (equal azt_polaczenie_zakladkowe_rodzaj_sruby "16")
      (azt_polaczenie_parametry_m16)
      (princ)
  )
    (if (equal azt_polaczenie_zakladkowe_rodzaj_sruby "20")
      (azt_polaczenie_parametry_m20)
      (princ)
  )
  (if (equal azt_polaczenie_zakladkowe_rodzaj_sruby "24")
      (azt_polaczenie_parametry_m24)
      (princ)
  )
  (if (equal azt_azt_polaczenie_zakladkowe_rodzaj_sruby "30")
      (azt_polaczenie_parametry_m30)
      (princ)
  )
  (princ)
)

(defun c:azt_polaczenie_zakladkowe_rysuj ()
  (azt_polaczenie_zakladkowe_parametry)
  (setq azt_polaczenie_zakladkowe_ilosc_srub_w_poziomie (getstring (strcat "\nPodaj ilosc srub w polaczeniu poziomo: <" azt_aktualne_polaczenie_zakladkowe_ilosc_srub_w_poziomie ">")))
  (if (equal azt_polaczenie_zakladkowe_ilosc_srub_w_poziomie "")
      (setq azt_polaczenie_zakladkowe_ilosc_srub_w_poziomie azt_aktualne_polaczenie_zakladkowe_ilosc_srub_w_poziomie)
      (princ)
  )
  (setq azt_polaczenie_zakladkowe_ilosc_srub_w_pionie (getstring (strcat "\nPodaj ilosc srub w polaczeniu pionowo: <" azt_aktualne_polaczenie_zakladkowe_ilosc_srub_w_pionie ">")))
  (if (equal azt_polaczenie_zakladkowe_ilosc_srub_w_pionie "")
      (setq azt_polaczenie_zakladkowe_ilosc_srub_w_pionie azt_aktualne_polaczenie_zakladkowe_ilosc_srub_w_pionie)
      (princ)
  )
)
  (setq azt_polaczenie_zakladkowe_aktualny_punktx "0")
  (setq azt_polaczenie_zakladkowe_aktualny_punkty "0")
(repeat (atoi azt_polaczenie_zakladkowe_ilosc_srub_w_poziomie)
  (command "_point" (list azt_polaczenie_zakladkowe_aktualny_punktx azt_polaczenie_zakladkowe_aktualny_punkty))
  (setq azt_polaczenie_zakladkowe_aktualny_punktx (+ (atoi azt_polaczenie_zakladkowe_aktualny_punktx) (atoi azt_polaczenie_parametr_p)))
  (setq azt_polaczenie_zakladkowe_aktualny_punkty (+ (atoi azt_polaczenie_zakladkowe_aktualny_punktx) (atoi azt_polaczenie_parametr_p)))
  (princ)  
)

(c:azt_polaczenie_zakladkowe_start)